# Generated by Django 2.0.6 on 2018-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180609_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.TextField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
